#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Terraform
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: Download Terraform
        get_url: url=https://dl.bintray.com/mitchellh/terraform/terraform_0.6.3_linux_amd64.zip dest=/root/terraform.zip mode=444
      - name: Unpack Terraform
        unarchive: src=/root/terraform.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/terraform

- name: Packer
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: Download Packer
        get_url: url=https://dl.bintray.com/mitchellh/packer/packer_0.8.6_linux_amd64.zip dest=/root/packer.zip mode=444
      - name: Unpack Terraform
        unarchive: src=/root/packer.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/packer

- name: AWS CLI
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: AWS CLI
        command: pip install --upgrade awscli

