#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Dump Environment
  hosts: all
  become: True
  tasks:
      - name: Display all variables/facts known for a host
        debug: var=hostvars[inventory_hostname]

- name: Nomad
  hosts: all
  become: True
  vars:
    nomad_version: 0.4.1
  tasks:
      - get_url: url=https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip dest=/root/nomad.zip mode=444
      - unarchive: src=/root/nomad.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/nomad

- name: Consul
  hosts: all
  become: True
  vars:
    consul_version: 0.7.0
  tasks:
      - get_url: url=https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip dest=/root/consul.zip mode=444
      - unarchive: src=/root/consul.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/consul

- name: Consul Template
  hosts: all
  become: True
  vars:
    version: 0.16.0
  tasks:
      - get_url: url=https://releases.hashicorp.com/consul-template/{{ version }}/consul-template_{{ version }}_linux_amd64.zip dest=/root/consul-template.zip mode=444
      - unarchive: src=/root/consul-template.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/consul-template

- name: Consul Replicate
  hosts: all
  become: True
  vars:
    version: 0.2.0
  tasks:
      - get_url: url=https://releases.hashicorp.com/consul-replicate/{{ version }}/consul-replicate_{{ version }}_linux_amd64.zip dest=/root/consul-replicate.zip mode=444
      - unarchive: src=/root/consul-replicate.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/consul-replicate
      
- name: Terraform
  hosts: all
  become: True
  vars:
    terraform_version: 0.7.5
  tasks:
      - get_url: url=https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip dest=/root/terraform.zip mode=444
      - unarchive: src=/root/terraform.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/terraform

- name: Packer
  hosts: all
  become: True
  vars:
    packer_version: 0.10.2
  tasks:
      - get_url: url=https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip dest=/root/packer.zip mode=444
      - unarchive: src=/root/packer.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/packer

- name: Vault
  hosts: all
  become: True
  vars:
    vault_version: 0.6.2
  tasks:
      - get_url: url=https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip dest=/root/vault.zip mode=444
      - unarchive: src=/root/vault.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/vault

- name: Vault SSH Helper
  hosts: all
  become: True
  vars:
    version: 0.1.2
  tasks:
      - get_url: url=https://releases.hashicorp.com/vault-ssh-helper/{{ version }}/vault-ssh-helper_{{ version }}_linux_amd64.zip dest=/root/vault-ssh-helper.zip mode=444
      - unarchive: src=/root/vault-ssh-helper.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/vault-ssh-helper
      
- name: AWS CLI
  hosts: all
  become: True
  tasks:
      - command: pip install --upgrade awscli

- name: AWS ECS CLI
  hosts: all
  become: True
  tasks:
      - get_url: url=https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest dest=/usr/local/bin/ecs-cli mode=555

- name: Install Tool Containers
  hosts: all
  become: False
  tasks:
      - file: path=/home/vagrant/GitHub owner=vagrant group=vagrant state=directory mode=755
      - file: path=/home/vagrant/bin owner=vagrant group=vagrant state=directory mode=755

      - git: repo=https://github.com/kurron/docker-packer.git dest=/home/vagrant/GitHub/docker-packer
      - file: src=/home/vagrant/GitHub/docker-packer/packer.sh path=/home/vagrant/bin/packer state=absent

      - git: repo=https://github.com/kurron/docker-aws-cli.git dest=/home/vagrant/GitHub/docker-aws-cli
      - file: src=/home/vagrant/GitHub/docker-aws-cli/aws.sh path=/home/vagrant/bin/aws state=absent

      - git: repo=https://github.com/kurron/docker-aws-ecs-cli.git dest=/home/vagrant/GitHub/docker-aws-ecs-cli
      - file: src=/home/vagrant/GitHub/docker-aws-ecs-cli/ecs.sh path=/home/vagrant/bin/ecs-cli state=absent

      - git: repo=https://github.com/kurron/docker-terraform.git dest=/home/vagrant/GitHub/docker-terraform
      - file: src=/home/vagrant/GitHub/docker-terraform/terraform.sh path=/home/vagrant/bin/terraform state=absent

      - git: repo=https://github.com/kurron/docker-vault.git dest=/home/vagrant/GitHub/docker-vault
      - file: src=/home/vagrant/GitHub/docker-vault/vault.sh path=/home/vagrant/bin/vault state=absent

      - git: repo=https://github.com/kurron/docker-nomad.git dest=/home/vagrant/GitHub/docker-nomad
      - file: src=/home/vagrant/GitHub/docker-nomad/nomad.sh path=/home/vagrant/bin/nomad state=absent

      - git: repo=https://github.com/kurron/docker-consul.git dest=/home/vagrant/GitHub/docker-consul
      - file: src=/home/vagrant/GitHub/docker-consul/consul.sh path=/home/vagrant/bin/consul state=absent

      - git: repo=https://github.com/kurron/docker-consul-template.git dest=/home/vagrant/GitHub/docker-consul-template
      - file: src=/home/vagrant/GitHub/docker-consul-template/consul-template.sh path=/home/vagrant/bin/consul-template state=absent

      - git: repo=https://github.com/kurron/docker-consul-replicate.git dest=/home/vagrant/GitHub/docker-consul-replicate
      - file: src=/home/vagrant/GitHub/docker-consul-replicate/consul-replicate.sh path=/home/vagrant/bin/consul-replicate state=absent

      - git: repo=https://github.com/kurron/docker-vault-ssh-helper.git dest=/home/vagrant/GitHub/vault-ssh-helper
      - file: src=/home/vagrant/GitHub/vault-ssh-helper/vault-ssh-helper.sh path=/home/vagrant/bin/vault-ssh-helper state=absent

      - file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Install Sysdig (Ubuntu)
  hosts: Ubuntu
  become: True
  tasks:
      - apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
      - apt_repository: repo='deb http://download.draios.com/stable/deb stable-$(ARCH)/' state=present mode=0644
      - apt: name=sysdig state=latest update_cache=true
