#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Terraform
  hosts: nobody
  sudo: True
  vars:
    terraform_version: 0.6.8
  tasks:
      - name: Download Terraform
        get_url: url=https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip dest=/root/terraform.zip mode=444
      - name: Unpack Terraform
        unarchive: src=/root/terraform.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/terraform

- name: Packer
  hosts: nobody
  sudo: True
  vars:
    packer_version: 0.8.6
  tasks:
      - name: Download Packer
        get_url: url=https://dl.bintray.com/mitchellh/packer/packer_{{ packer_version }}_linux_amd64.zip dest=/root/packer.zip mode=444
      - name: Unpack Terraform
        unarchive: src=/root/packer.zip dest=/usr/local/bin copy=no owner=root group=root mode=555 creates=/usr/local/bin/packer

- name: AWS CLI
  hosts: nobody
  sudo: True
  tasks:
      - name: AWS CLI
        command: pip install --upgrade awscli

- name: AWS ECS CLI
  hosts: nobody
  sudo: True
  tasks:
      - name: Download CLI
        get_url: url=https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest dest=/usr/local/bin/ecs-cli mode=555

- name: Install Tool Containers
  hosts: Ubuntu
  sudo: False
  tasks:
      - name: Checkout Packer Container
        git: repo=https://github.com/kurron/docker-packer.git dest=/home/vagrant/GitHub/docker-packer
      - name: Soft link Packer Container
        file: src=/home/vagrant/GitHub/docker-packer/packer.sh path=/home/vagrant/bin/packer state=link
      - name: Checkout AWS CLI Container
        git: repo=https://github.com/kurron/docker-aws-cli.git dest=/home/vagrant/GitHub/docker-aws-cli
      - name: Soft link AWS CLI Container
        file: src=/home/vagrant/GitHub/docker-aws-cli/aws.sh path=/home/vagrant/bin/aws state=link
      - name: Checkout AWS ECS CLI Container
        git: repo=https://github.com/kurron/docker-aws-ecs-cli.git dest=/home/vagrant/GitHub/docker-aws-ecs-cli
      - name: Soft link AWS ECS CLI Container
        file: src=/home/vagrant/GitHub/docker-aws-ecs-cli/ecs.sh path=/home/vagrant/bin/ecs-cli state=link
      - name: Checkout Terraform Container
        git: repo=https://github.com/kurron/docker-terraform.git dest=/home/vagrant/GitHub/docker-terraform
      - name: Soft link Terraform Container
        file: src=/home/vagrant/GitHub/docker-terraform/terraform.sh path=/home/vagrant/bin/terraform state=link
      - name: Checkout Vault Container
        git: repo=https://github.com/kurron/docker-vault.git dest=/home/vagrant/GitHub/docker-vault
      - name: Soft link Vault Container
        file: src=/home/vagrant/GitHub/docker-vault/vault.sh path=/home/vagrant/bin/vault state=link
      - name: Set permissions on the home directory
        file: path=/home/vagrant owner=vagrant group=vagrant recurse=true state=directory

- name: Install Sysdig
  hosts: Ubuntu
  sudo: True
  tasks:
      - name: Download the signing key
        apt_key: url=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public state=present
      - name: Add the Apt repository
        apt_repository: repo='deb http://download.draios.com/stable/deb stable-$(ARCH)/' state=present
      - name: Install Sysdig
        apt: name=sysdig state=latest update_cache=true
